[General]

; Screen blood effect applied when the player receives damage. 0 = Disabled, 1 = Vanilla
iEffectReceive = 1

; Screen blood effect applied when the player deals damage. 0 = Disabled, 1 = Screen Blood Enhanced
iEffectDeal = 1


[Animation]

; Set screen wipe animation variant to use while the player is not in combat. 0 = Default, 1 = Alt (Faster)
iVariantDefault = 0

; Set screen wipe animation variant to use while the player is in combat. 0 = Default, 1 = Alt (Faster)
iVariantCombat = 1

; Play the screen wipe animation on the left arm only, allowing the game to control the right arm.
bLeftArmOnly = 1

; Force the player to first person while playing the animation.
bForceFirstPerson = 1


[Controls]

; Wipe Screen keybind. (Default: H)
; Key code list located here: https://ck.uesp.net/wiki/Input_Script#DXScanCodes
iKeybind = 35


[Visibility]

; Distance where splatters will start to appear. (In meters)
fDistance = 4

; Heading angle between the player and the hit target where splatters will start to appear. (In degrees)
fHeadingAngle = 70

; Minimum damage value that needs to be dealt for a splatter to appear.
fDamageMin = 2

; Maximum damage value used in the splatter calculation.
fDamageMax = 20

; Toggle first person blood splatters.
b1stPerson = 1

; Toggle third person blood splatters.
b3rdPerson = 0


[BloodSplatter]

; Default number of screen blood splatters.
iCount = 10

; Default splatter duration. (In seconds)
fDuration = 20

; Attack type multipliers.
fUnarmed = 0.6
fBlunt = 0.8
fBlade = 1
fProjectile = 0.8
fPowerAttack = 2

; Body damage multipliers.
fLimbDismembered = 2

; Controls the size and opacity of the generated splatters.
fSizeMin = 0.8
fSizeMax = 1.2
fAlphaMin = 0.6
fAlphaMax = 1

; Controls the size and opacity of the splatter flares.
fFlareSize = 1
fFlareAlpha = 0.95
